
IDX_ACTION_LEFT = 0
IDX_ACTION_DOWN = 1
IDX_ACTION_RIGHT = 2
IDX_ACTION_UP = 3
IDX_ACTION = [IDX_ACTION_LEFT, IDX_ACTION_DOWN, IDX_ACTION_RIGHT, IDX_ACTION_UP]

INITIAL_ACTION_UP = 'U'
INITIAL_ACTION_DOWN = 'D'
INITIAL_ACTION_RIGHT = 'R'
INITIAL_ACTION_LEFT = 'L'
INITIAL_ACTION = [INITIAL_ACTION_LEFT, INITIAL_ACTION_DOWN, INITIAL_ACTION_RIGHT, INITIAL_ACTION_UP]

STR_ACTION_UP = 'Up'
STR_ACTION_DOWN = 'Down'
STR_ACTION_RIGHT = 'Right'
STR_ACTION_LEFT = 'Left'
STR_ACTION = [STR_ACTION_UP, STR_ACTION_DOWN, STR_ACTION_RIGHT, STR_ACTION_LEFT]

INITIAL_ENV_START = 'S'
INITIAL_ENV_GOAL = 'G'
INITIAL_ENV_FLOOR = 'F'
INITIAL_ENV_WALL = 'H'



